language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
install:
 - pip install -U -i https://pypi.doubanio.com/simple pip setuptools wheel
 - pip install -U -i https://pypi.doubanio.com/simple poetry coverage
 - poetry install
script: poetry run  nosetests --with-coverage --cover-package=schema_validator
